services:
  aiq:
    container_name: aiq--controller-shelves
    image: ghcr.io/fvsqr-netapp/aiq--controller-shelves:latest
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    volumes:
      - .serials:/opt/aiq/serials
      - .:/csv
      - ./controller-shelves.sh:/controller-shelves.sh